In [1]:
import pandas as pd
import numpy as np
import math
from itertools import chain

In [2]:
df = pd.read_csv('/Users/Maryam/Documents/summer-Research-2020/ImgClassAnalysis/imgClassificationData.csv')

In [64]:
# Temporary way of pulling out the data we actually want to analyze. Confirm with Cindy first. 
# check if postQs are answered
# where/when to drop the nan values
# data = df.loc[df['Finished'] == 'True']
data = df.iloc[[124]]

#  want to separate the data for inv and orig for each subject

In [65]:
# traversing through each row to pull out each subjects data
for index,subject_data in data.iterrows():
    
    # need to aggregate allStims and allSelections for each subject
    allStimuli = data['allStims1']
    allSelects = data['selections1']
    for i in range(2,21):
        stimCol = data['allStims' + str(i)]
        allStimuli = pd.concat([stimCol,allStimuli])
        

        selectsCol = data['selections' + str(i)]
        allSelects = pd.concat([selectsCol,allSelects])
    
#  create new empty df
    subject_table = data[index:index+1]
    
# selecting every third entry for response column
    response_arr = allSelects[1:]
    allStimuli = allStimuli.tolist()
    allSelects = allSelects.tolist()
    for i in range(len(allStimuli)):
        allStimuli[i] = allStimuli[i].split(',')
        allSelects[i] = allSelects[i].split(',')
    allStimuli = list(chain.from_iterable(allStimuli))
    allSelects = list(chain.from_iterable(allSelects))
    allSelects = allSelects[1:][::3]
#     allSelects = pd.DataFrame(allSelects[1:],columns=['responses'], index=[i for i in range(0,2999)]).iloc[::3, :]
    
# trying to figure out how to select inv and orig based on 37 and 39 keycode
    image = []
    for i in range(len(allSelects)):
        for j in allStimuli[::2]:
            if i == 37:
                if (j.find('inv') != -1):
                    image.append(-1)
                else:
                    image.append(1)
            elif i == 39:
                if (j.find('inv') != -1):
                    image.append(-1)
                else:
                    image.append(1)

    
#  creating new desired tables inv and orig
#  need to figure out how to save every df with every iteration
# -1 or 1 if inv or orig, left=37 right=39
    desired = pd.DataFrame(columns=['stimulus', 'response', 'subject'], index=[i for i in range(0,1000)])
    desired['stimulus'] = ...
    desired['response'] = allSelects
    desired['subject'] = 'Cindy'

len(allSelects), len(allStimuli[::2]), len(image)
desired

     stimulus response subject
0    Ellipsis       37   Cindy
1    Ellipsis       39   Cindy
2    Ellipsis       39   Cindy
3    Ellipsis       39   Cindy
4    Ellipsis       37   Cindy
..        ...      ...     ...
995  Ellipsis       39   Cindy
996  Ellipsis       37   Cindy
997  Ellipsis       39   Cindy
998  Ellipsis       37   Cindy
999  Ellipsis       37   Cindy

[1000 rows x 3 columns]